export const SET_ERROR ='NOTIFICATIONS/SET_ERROR';
export const SET_SUCCESS ='NOTIFICATIONS/SET_SUCCESS';
export const SET_LOADING ='NOTIFICATIONS/SET_LOADING';
export const CLEAR_LOADING ='NOTIFICATIONS/CLEAR_LOADING';
export const SET_UPDATE='NOTIFICATIONS/SET_UPDATE';
export const SET_DELETE='NOTIFICATIONS/SET_DELETE';